Develop
Melnikova26/todo_next.ts pull request #1
Opened 2023-08-10 09:53 UTC by Melnikova26

2023-08-10 10:53 UTC, IRaccoonI requested changes

2023-08-10 10:53 UTC, IRaccoonI commented on backend/src/db.ts
> +const sequelize = new Sequelize("todo", "postgress", "postgress", {
все креды на вход нужно вынести в .env, старайся всё что относится к настройке проекта(ссылки на бд, на бэк, порты, какие нибудть api-key'сы) выносить в энвы, тут 2 причины: 1. ты это всё палишь в репе, и это видят другие 2. ты выносишь это всё в одно место, следовательно быстрее можно настроить проект под себя

2023-08-10 10:53 UTC, IRaccoonI commented on backend/src/index.ts
> +sequelize
выглядит немного странно, ты бд запускаешь после того как зарегала все руты, т.е. приложение будет и без бд работать, запускай приложение в функции, там запускай бд -> регай руты, что то одно не работает, ничего не работает)

2023-08-10 10:53 UTC, IRaccoonI commented on backend/src/models/TodoModel.ts
> +TodoModel.init(
перепиши это на декораторы пожалуйста https://github.com/sequelize/sequelize-typescript тут есть всё что нужно
точно не уверен, но могут типы потерятся, если оставить так

2023-08-10 10:53 UTC, IRaccoonI commented on docker-compose.yml
> +  postgres:
сделай отдельный volume под постгрес), задача на ресёрч так сказать, если что пиши

2023-08-10 10:53 UTC, IRaccoonI commented on frontend/components/TheFooter.tsx
> +const TheFooter = () => {
```suggestion
const Footer = () => {
```

2023-08-10 10:53 UTC, IRaccoonI commented on frontend/components/TheHeader.tsx
> +const TheHeader = () => {
```suggestion
const Header = () => {
```

2023-08-10 10:53 UTC, IRaccoonI commented on frontend/components/TodoItem.tsx
> +  const handleEdit = (e: ChangeEvent<HTMLInputElement>) => {
где то через useCallback, где то просто лямбда, лучше пиши как то одинаково, лучше через useCallback конечно)

2023-08-10 10:53 UTC, IRaccoonI commented on frontend/components/TodoPage.tsx
> +  const [filteredNotes, setFilteredNotes] = useState<NoteType[]>([]);
выглядит как `useMemo` а не `useState`

2023-08-10 10:53 UTC, IRaccoonI commented on frontend/components/TodoSearch.tsx
> +  const [search, setSearch] = useState<string>("");
```suggestion
  const [search, setSearch] = useState("");
```
тип берётся из значений, нет смысл писать явно тип, если он будет такой же как и поставит сам useState

2023-08-11 10:11 UTC, Melnikova26 commented on backend/src/models/TodoModel.ts
> +TodoModel.init(
поправила

2023-08-11 10:11 UTC, Melnikova26 commented on docker-compose.yml
> +  postgres:
сделала. Да оказывается данные терялись после того как останавливала контейнеры и заново запускала. Сейчас вроде все ок

2023-08-11 10:12 UTC, Melnikova26 commented on frontend/components/TheFooter.tsx
> +const TheFooter = () => {
поправила)

2023-08-11 10:12 UTC, Melnikova26 commented on frontend/components/TheHeader.tsx
> +const TheHeader = () => {
поправила)

2023-08-11 10:12 UTC, Melnikova26 commented on frontend/components/TodoItem.tsx
> +  const handleEdit = (e: ChangeEvent<HTMLInputElement>) => {
поправила

2023-08-11 10:12 UTC, Melnikova26 commented on frontend/components/TodoPage.tsx
> +  const [filteredNotes, setFilteredNotes] = useState<NoteType[]>([]);
сделала через useMemo

2023-08-11 10:13 UTC, Melnikova26 commented on frontend/components/TodoSearch.tsx
> +  const [search, setSearch] = useState<string>("");
поняла, поправила

2023-09-14 08:00 UTC, merged